version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    restart: always
    # cpus: 4
    # cpu_count: 4
    # cpuset: 0-3
    labels: 
      - "traefik.enable=true"
     # - "traefik.port=8080"
      - "traefik.http.services.dummyService.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik_http.service=api@internal"
      - "traefik.http.routers.monitor.rule=Host(`monitor.example.org`)"
      - "traefik.http.routers.monitor.entrypoints=websecure"
      - "traefik.http.routers.monitor.tls.certresolver=myresolver"
     # - "traefik.http.middlewares.test-auth.basicauth.users=tangcuyuha:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=me@expoli.tech"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--metrics.prometheus=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "8080:8080"
    network_mode: host
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.org`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: traefik
