version: "2"

services:
  grafana:
    image: grafana/grafana
    #ports:
    #  - 3000:3000
    expose:
      - 3000
    user: "472"
    restart: always
    logging: 
      options: 
        max-size: 1m
    environment: 
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
      - TZ="Asia/Shanghai"
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.grafana.rule=Host(`grafana.example.org`)"
      # - "traefik.http.services.grafana.loadbalancer.server.port=5212"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks: 
      - proxy-tier

networks:
  proxy-tier:
    external:
      name:  traefik

